elastic/elastic-agent-changelog-tool

- README.md
- cmd/new.go
- go.mod
- internal/changelog/fragment/creator.go
- internal/changelog/fragment/creator_internal_test.go
- internal/changelog/fragment/fragment.go
- internal/gitreporoot/gitreporoot.go
- internal/gitreporoot/gitreporoot_test.go
- internal/settings/settings.go
- main.go
Adding **changelog fragment** struct and `FragmentCreator` struct capable of generating a changelog fragment.
~Please note that the final changelog fragment content is still to be finalized.~ Content has been finalized.
> Add Changelog Fragment creation

- .ci/Jenkinsfile
- .github/workflows/pull-request.yaml
As per discussion with @v1v we can move lint stage to GitHub Actions, to
provide faster feedback and speed up the build & test phases.
This commit removes the `Lint` stage from Jenkins and add the missing
tasks in `lint` GitHub Actions job.
Note that `go vet` is included in `golangci-lint`.
> Remove Lint stage from Jenkins

- cmd/build.go
- cmd/build_test.go
- go.mod
- internal/changelog/builder.go
- internal/changelog/changelog.go
- internal/changelog/entry.go
- internal/changelog/entry_test.go
- internal/changelog/fragment/file.go
- internal/changelog/fragment/file_test.go
- internal/changelog/fragment/testdata/1648040924-breaking-change.yaml
- internal/changelog/fragment/testdata/1648040928-enhancement.yaml
- internal/changelog/kind.go
- internal/changelog/testdata/1648040928-breaking-change.yaml
- internal/changelog/testdata/1648040928-bug-fix.yaml
- internal/changelog/testdata/1648040928-deprecation.yaml
- internal/changelog/testdata/1648040928-enhancement.yaml
- internal/changelog/testdata/1648040928-feature.yaml
- internal/changelog/testdata/1648040928-known-issue.yaml
- internal/changelog/testdata/1648040928-other.yaml
- internal/changelog/testdata/1648040928-security.yaml
- internal/changelog/testdata/1648040928-unknown.yaml
- internal/changelog/testdata/1648040928-upgrade.yaml
- internal/settings/settings.go
- main.go
This PR is based on #13 so it **must** be merged after that. 
It needs #17 to be merged before merge.
Closes #20.
Add `changelog.Builder` struct implementing the logic to build a changelog YAML representation where **changelog fragments** are deduplicated and merged into a list of `changelog.Entry`.
> Implement changelog builder

- .github/workflows/pull-request.yaml
- Makefile
- README.md
Running `go run ...go-licenser` updates the `go.mod` file. Each time a developer was running `make licenser` the go.mod was updated, but those changes were not to be committed, otherwise the CI would complain.
Solving this issue by using the `go-licenser` binary directly.
> Fix go-licenser go.mod changes

- cmd/build.go
- cmd/build_test.go
- internal/changelog/builder.go
Add `--version` flag to `build` command (was hardcoded to `8.2.1` before).
Fix tests, that were passing but not correctly testing the build functionality.
> Changelog builder improvements

- internal/github/find-pr.go
- internal/github/find-pr_test.go
Concerns Issue #11 
Heuristics should be constantly updated as more patterns get found.
Examples: 
1. Using `b8cf1e7995393db980ffffad4504a5175de450b8` commit hash from https://github.com/elastic/beats/pull/30626 correctly shows `29209` as being the main PR.
> Add heuristics

- cmd/find_pr.go
- cmd/pr_has_fragment.go
- cmd/pr_has_fragment_test.go
- cmd/root.go
- internal/github/find-file-in-pr.go
- internal/github/find-file-in-pr_test.go
- internal/github/interfaces.go
- internal/github/testdata/fixtures/TestFindFileInPR.yaml
- internal/github/testdata/fixtures/TestFindFileInPR_PrIsNotFound.yaml
- internal/github/testdata/fixtures/TestFindFileInPR_failureCase.yaml
- main.go
This PR adds a `pr-has-fragment` command that can check if in a given PR is present a file identifiable as a changelog fragment (identification is done checking for presence of an added file in the `changelog_path` setting location).
The command either exists with `0` without output when at least one PR fragment is found or exits with `1` when no PR fragment is found.
Closes #38
Testing has been done with:
- `elastic-agent-changelog-tool pr-has-fragment --repo elastic-agent-changelog-tool 29`
- `elastic-agent-changelog-tool pr-has-fragment --repo elastic-agent-changelog-tool 33`
> add command to verify fragment in PR

- cmd/pr_has_fragment_test.go
- internal/settings/settings.go
Small changes to `cmd` package tests to suppress log messages and avoid variable override discovered in #48
> Enhance cmd tests

- internal/changelog/builder.go
- internal/changelog/builder_internal_test.go
- internal/changelog/builder_test.go
In https://github.com/elastic/elastic-agent-changelog-tool/commit/cb365b667def5e7018305074a82cfddb43091a36 @LucianPy discovered that the FS walker collecting fragments in `changelog.Build` funcition was collecting also the `.gitkeep` file, and thus broke when trying to parse it.
This PR extracts the walker function, add tests to it and add an exclusion filter based on file extension: it collects only files with `.yaml` extension.
> Ignore non YAML file from fragment collection

- .gitignore
- .goreleaser.yml
- Makefile
- docs/release-process.md
Part of #42
`elastic-package` leverages GoReleaser to build and release its versions.
This PR adds GoReleaser configuration to build binaries and create GitHub released based on Git tags.
It misses the CI automation.
> Add goreleaser release process

- go.mod
- internal/changelog/asciidoc-template.asciidoc
- internal/changelog/entry.go
- internal/changelog/file.go
- internal/changelog/renderer.go
- internal/changelog/renderer_internal_test.go
- internal/changelog/renderer_test.go
This PR provides the first implementation of the default changelog renderer.
The default renderer renders Asciidoc following the format of https://github.com/elastic/observability-docs/blob/5e2f16b351769a2d9ed7373d5e3290c16498eefa/docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
Closes #46
> Implement default renderer

- go.mod
- go.sum
- internal/changelog/builder.go
- internal/changelog/builder_test.go
- internal/changelog/entry.go
- internal/changelog/renderer.go
- internal/changelog/testdata/fixtures/TestFindIssues.yaml
- internal/github/client.go
- internal/github/interfaces.go
Closes #41 
REST does not provide a way to get linked issues so `githubv4` had to be used as a dependency here to extract the data using GraphQL.
Because of this, at some point, all REST code has to be changed to GraphQL for maintenance reasons.
***To be discussed what to do in case of multiple issues from the user's perspective.
> Automate issue fragment field collection

- internal/changelog/entry.go
`changelog.Entry` must keep track of the `Repository` field to
know the repository an issue or PR number refers to.
> Track repository in `changelog.Entry`

- cmd/build.go
- cmd/find_pr.go
- cmd/new.go
- cmd/pr_has_fragment.go
- cmd/render.go
- cmd/root.go
Most cmds did not have a short description (shown in `--help`)
> Fix cmds short descriptions

- main.go
Command was implemented but not added to available commands, thus
unusable.
> Add `render` cmd to CLI

- .github/workflows/pull-request.yaml
- tools/CHANGELOG.next.asciidoc
- tools/asciidoc_to_fragments.py
Closes #67
Script that converts asciidoc changelog from `elastic-agent` repository to fragments.
It also includes a stripped down version of the `CHANGELOG.next.asciidoc` to easily test it.
This works fine for `CHANGELOG.next.asciidoc`.
One edge case to be fixed in `CHANGELOG.asciidoc` (malformed changelog file for pull 24128).
Planned future updates:
> Add asciidoc changelog to fragments script

- cmd/build.go
- cmd/build_test.go
- internal/settings/settings.go
This PR updates `build` command to- use a fixed consolidated changelog filename (instead of relying on a setting) with the same name as the version being consolidated. It also updates the destination folders for consolidated changelog and rendered changelog to `changelog`, to keep everything scoped as neither is a final product.
> Coherent changelog locations

- changelog/fragments/1662383510-Fix-issue-automation.yaml
- internal/changelog/builder.go
Closes #85 
My mistake here, if the PR automation happens it's correct to actually check `b.changelog.Entries[i]` instead of `entry`.
Thanks @endorama for spotting this.
> Fix issue automation

- .ci/jobs/defaults.yml
- .ci/jobs/elastic-agent-changelog-tool-mbp.yml
- README.md
Use `fleet-ci`  to scale horizontally the CI.
In order to distribute the load and reduce a single point of failure,
> jjbb: use fleet-ci

- changelog/fragments/1663757086-Fix-build-logic-for-Github-API-calls.yaml
- internal/changelog/builder.go
- internal/changelog/builder_test.go
Closes #108 
@endorama discovered a bug following the transition to URLs for pr/issue fields:
Github API calls were still using the `owner` and `repo` flag.
Now the URL is parsed and the `owner` and `repo` extracted are passed further.
`url` library was used here since the `Path` field makes this less error prone. 
For example, parsing will work with or without the "https://" prefix.
> Fix build logic

- docs/usage.md
> Add docs for prereleases usage

- changelog/fragments/1666868151-Add-multiple-component-support.yaml
- config.yaml
- internal/changelog/asciidoc-template.asciidoc
- internal/changelog/renderer.go
> Add multiple component support

- changelog/fragments/1667229980-handle-missing-failure-case-to-URL-extraction.yaml
- internal/changelog/builder.go
The current code check to determine a valid URL didn't take into
account this particular case which resulted in a panic at runtime.
> handle missing failure case to URL extraction

- changelog/fragments/1666956886-Add-changelong-lint-command.yaml
- cmd/changelog_lint.go
- internal/changelog/linter.go
- internal/changelog/linter_test.go
- main.go
Closes #45
Cherry-pick of `a7d4406` is required. PR #116 should be merged first.
> Add changelog lint cmd

- .ci/Jenkinsfile
- .goreleaser.yml
- Dockerfile
Support docker images.
Additionally, support go-releaser for PRs in the CI by using `--snapshots`, to avoid publishing anything, this should help us to detect breaking changes in the go-releaser before any release
Requires https://github.com/elastic/elastic-agent-changelog-tool/pull/122
> release: provide docker images

- docs/github-authentication.md
- docs/usage.md
Closes #121
- add github auth docs
- document where github auth is needed
> provide docs for GitHub auth

- changelog/fragments/1673258661-Support-rendering-description.yaml
- internal/assets/asciidoc-template.asciidoc
- internal/changelog/fragment/creator_internal_test.go
- internal/changelog/fragment/template.yaml
- internal/changelog/renderer.go
- internal/changelog/renderer_test.go
- internal/changelog/testdata/1648040928-breaking-change.yaml
- internal/changelog/testdata/1648040928-known-issue.yaml
Add support for rendering description when entry kind is `breaking-change` or `known-issue`, as supported by the current release notes.
Description is within a collapsible field and has an inline link based on PR number (for `breaking-change`) or Issue number (for `known-issue`).
> Support rendering description for breaking changes and known issues

- .github/workflows/pull-request.yaml
GitHub deprecated set-output command, replacing it with an environment
variable approach.
See
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Patch deprecated set-output command in CI

- changelog/fragments/1678187521-Render-kind-upgrade.yaml
- internal/assets/asciidoc-template.asciidoc
- internal/changelog/renderer_test.go
> Render `upgrade` kind

- changelog/fragments/1678182005-Render-description-for-kind-feature.yaml
- internal/assets/asciidoc-template.asciidoc
- internal/changelog/renderer_test.go
This PR adds rendering of `description` field for changelog fragments of kind `feature`.
Closes #133
> Render `feature` description

- .github/workflows/pull-request.yaml
This commit increases the timeout and changes the flag for the linter to scan the whole file, similar to how we do it in other repositories.
> Increase the timeout for the lint task

- changelog/fragments/1687169387-fragment-filename-sanitize.yaml
- internal/changelog/fragment/creator.go
- internal/changelog/fragment/creator_internal_test.go
Using `:` char in filenames is only supported on Linux, thus this may break changelog consolidation after creating a changelog fragment (either locally or in CI).
This PR sanitize filename for `:` char too, removing it.
More about supported chars in filenames: https://stackoverflow.com/a/35352640
> Remove `:` from filenames

- changelog/fragments/1686835318-new-title-optional.yaml
- cmd/new.go
New changelog fragments are often created while working inside a  git branch. This change makes the title argument to the `new` sub-command optional (via the optional `--title` flag), defaulting the title to the name of the current git branch.
```
$ ./elastic-agent-changelog-tool new
2023/06/20 09:16:21 Using config file: /Users/shaunak/development/github/elastic-agent-changelog-tool/config.yaml
2023/06/20 09:16:21 created fragment /Users/shaunak/development/github/elastic-agent-changelog-tool/changelog/fragments/1687277781-new-title-optional.yaml
$ git symbolic-ref --short HEAD
new-title-optional
```
```
$ ./elastic-agent-changelog-tool new single
2023/06/20 09:16:46 Using config file: /Users/shaunak/development/github/elastic-agent-changelog-tool/config.yaml
2023/06/20 09:16:46 created …
```
> [`new` sub-command] Default title to git branch name

- .buildkite/hooks/post-checkout
- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-exit
- .buildkite/pipeline.yml
- .buildkite/scripts/build.sh
- .buildkite/scripts/pre-install-command.sh
- .buildkite/scripts/prepare-report.sh
- .buildkite/scripts/release.sh
- .buildkite/scripts/snapshot.sh
- .buildkite/scripts/test.sh
- .buildkite/scripts/tooling.sh
- .goreleaser.yml
- catalog-info.yaml
> Migration to buildkite

- changelog/fragments/1695368036-remove-single-quote-from-file-names.yaml
- internal/changelog/fragment/creator.go
- internal/changelog/fragment/creator_internal_test.go
Single quotes breaks go get thus they need to be removed from fragments file names.
Close https://github.com/elastic/elastic-agent-changelog-tool/issues/162
> Remove single quote from file names

- .github/workflows/pull-request.yaml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
> security: add permissions block to workflows
