elastic/elastic-agent-changelog-tool

.ci/jobs/defaults.yml
.ci/jobs/elastic-agent-changelog-tool-mbp.yml

A new project has been added to the CI.

[jjbb][beats-ci] elastic-agent-changelog-tool

---

Makefile
cmd/version.go
cmd/version_test.go
internal/version/version.go
internal/version/version_test.go
main.go

Closes #19
Add `version` internal package, update make target and provide `version` command.

Add version command

---

go.mod
internal/changelog/fragment/creator.go
internal/changelog/fragment/creator_internal_test.go
internal/changelog/fragment/fragment.go
internal/changelog/fragment/template.go
internal/changelog/fragment/template.yaml

Update changelog fragment structure to a different value and provide a text template with guidelines.

Update Changelog Fragment structure

---

internal/settings/settings.go
internal/settings/xdg.go
internal/settings/xdg_test.go

Improvements to `settings` package (fix linter and cleanup unnecessary code)

Improve settings

---

CONTRIBUTING.md
README.md
docs/install.md

Add installation and contributing docs.
Closes #26

Installation and contributing docs

---

README.md
changelog/0.1.0.yaml
changelog/fragments/1649924282-changelog-fragment-creation.yaml
changelog/fragments/1649924372-version-command.yaml
changelog/fragments/1649924436-update-changelog-fragment-structure.yaml
changelog/fragments/1649924529-add-find-pr-command.yaml
changelog/fragments/1649924600-implement-consolidated-changelog-builder.yaml
docs/concepts.md
docs/configuration.md
docs/getting-started.md
docs/glossary.md
docs/usage.md

Add usage docs and concepts.
Closes #27

Provide usage docs

---

tools/asciidoc_to_fragments.py

If the `pr` and `issue` fields are from different repositories, the script will no longer skip and instead generate a fragment using the `pr` field only.

Update changelog to fragments script logic

---

.github/workflows/pull-request.yaml

Force ourself to use fragments! 
Dogdfood `pr-has-fragment` to check for fragment presence in each PR on this repo.

add changelog fragments check

---

changelog/fragments/1662369001-Fix-logic-in-pr-has-fragment.yaml
internal/github/find-file-in-pr.go

- Closes #82 
I propose we first merge the fix and then retry testing #81 to see if it works.

Fix pr-has-fragment logic

---

changelog/fragments/1662992167-Update-gopkg.in-yaml-to-v3.0.1.yaml
go.mod
go.sum

Update to get over the security issue with v3.0.0

update gopkg.in/yaml to v3.0.1

---

cmd/pr_has_fragment.go

Add pr-has-fragment failure guidance

---

tools/asciidoc_to_fragments.py

Changelog conversion script fix issue link

---

tools/asciidoc_to_fragments.py

Some usaged docs
Print SHA1 for generated files
Do not add repository field

Changelog conversion script improvements and bugfix

---

tools/asciidoc_to_fragments.py

Filename sanitization does not currently create filenames valid on Windows (observed in checkout failures in Elastic Agent repo CI)
Closes #103

Changelog conversion script filename sanitization

---

Makefile
changelog/fragments/1664192272-Add-config-capabilities-for-owner-and-repository.yaml
cmd/build.go
cmd/find_pr.go
cmd/helpers.go
cmd/pr_has_fragment.go
cmd/root.go
config.yaml
go.mod
internal/settings/settings.go

Closes #88, #87
I've added a struct for the config instead of loading the fields into memory. 
The priority is flags > config values > default values.

Add config file

---

README.md

Adjust docs/install.md to point to to install docs

---

.ci/Jenkinsfile

this will help with pushing the docker images

ci: docker login

---

.github/workflows/pull-request.yaml

Update golangci-lint in CI to 1.51.2

---

docs/install.md

add docker to install docs

---

tools/requirements.txt

Update requests and urllib3 python libraries

Update requests and urllib3 version to fix vulnerabilities reported by snyk
